# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Hardware
  items:
    - label: 'SDT340'
      link: '/hardware/sdt340'
- label: Software
  items:
    - label: 'Vigilant'
    items:
    - label: 'Dashboard'
      link: '/software/vigilant-dashboard'
    items:
    - label: 'Vigilant Manual'
      link: '/software/vigilant-manual'
- label: Usage
  items:
    - label: 'Creating docs'
      link: '/usage/creating-docs'
    - label: 'Navigation'
      link: '/usage/navigation'
    - label: 'Shadowing'
      link: '/usage/shadowing'
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: 'Github'
      link: https://github.com/rocketseat/gatsby-themes
