# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: SDT340
  items:
    - label: 'User Manual'
      link: '/hardware/sdt340'
- label: Vigilant
  items:
    - label: 'Dashboard'
      link: '/software/vigilant/vigilant-dashboard'
    - label: 'User Manual'
      link: '/software/vigilant/vigilant-manual'
- label: Sonavu
  items:
    - label: 'User Manual'
      link: '/hardware/sonavu/sonavu-manual'
- label: Usage
  items:
    - label: 'Creating docs'
      link: '/usage/creating-docs'
    - label: 'Navigation'
      link: '/usage/navigation'
    - label: 'Shadowing'
      link: '/usage/shadowing'
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: 'Github'
      link: https://github.com/rocketseat/gatsby-themes
